#!/bin/bash

# A bash script to block all communication with the given domain
# by routing attempts to access it to localhost. Will block access
# to the site unless you're running a local copy. Overwrites /etc/hosts
# and is thus, very likely, highly unsafe. If you wish to run it
# without having to sudo, add this script to the list of scripts
# which don't prompt for sudo access.

HOSTFILE=/etc/hosts
TMPHOSTS=/tmp/fakehosts
BACKUP=~/Backups/hosts

for site in "facebook.com" "reddit.com"
do
  cp $HOSTFILE $BACKUP;
  dummy=`grep $site $HOSTFILE`;
  case $? in
    1)  echo "127.0.0.1	" $site >> $HOSTFILE ;;
    0) 
      sed "/$site/d" $HOSTFILE > $TMPHOSTS;
      mv $TMPHOSTS $HOSTFILE;;
    *) echo "Grep failed.";;
  esac
done

