#!/bin/sh

# A bash script to block all communication with the given domain
# by routing attempts to access it to localhost. Will block access
# to the site unless you're running a local copy. Overwrites /etc/hosts,
# so use at your own risk :)

# Writes to a backup file, /etc/hosts.bak 

HOSTFILE=/etc/hosts

if [ ! -w "$HOSTFILE" ]; then
  >&2 echo "productivity requires write privileges to ${HOSTFILE}."
  exit 1
fi

# Saves the backup
cp "$HOSTFILE" "${HOSTFILE}.bak"

PRODUCTIVITY="off"

for site in "facebook.com" "reddit.com" "smbc-comics.com" "xkcd.com"
do
  found=$(grep -P "127.0.0.1\t${site}" $HOSTFILE)
  if [ -z "$found" ]; then
    PRODUCTIVITY="on"
    printf "127.0.0.1\t%s www.%s\n" "$site" "$site" >> $HOSTFILE
  else
    sed -i -r "/127.0.0.1\t(www\.)?$site/d" $HOSTFILE
  fi
done

echo "Productivity mode: $PRODUCTIVITY"
